spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rootroot
    url: jdbc:mysql://localhost:3306/newtasktracker?serverTimezone=UTC
    platform: mysql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect